### ISSUE TITLE
Ollama NOT working localy, codespace, docker

### ISSUE THREAD

**Issue by rony432** [wandb/openui#32]
the main problem is that OPENAI package is TAKING priority over ollama. keep saying API key
all projects that using openai official package have this issue with ollama.

https://github.com/wandb/openui/issues/18#issuecomment-2034503485

please add Ollama server option to force it in OpenUI setting. by default its not checking for ollama just says OPENAI KEY missing/wrong

**Comment by BeeTwenty** [comment]
![Snag_2f24404a](https://github.com/wandb/openui/assets/43971937/fda6924a-0035-4f06-a466-52ea051896de)
![Snag_2f245b83](https://github.com/wandb/openui/assets/43971937/2a4c5eae-bf25-4376-84cb-4f281302f69c)


i cannot access Ollama either

**Comment by BeeTwenty** [comment]
i have set it to xxx in the docker run command

**Comment by rony432** [comment]
latest update working, thank you.(on codespace is very slow, as usual 👍 :)


inside terminal pull models for ollama first
run this
export OPENAI_API_KEY=xxx
then
python -m openui .
in main folder

**Comment by hirenchauhan2** [comment]
I did the local installations of Ollama with codellama model. I did docker setup, but it was not able to connect to Ollama server to fetch the list of models.  I used venv and installed the packages locally, and ran the server locally.

I got the models list from Ollama. But, the completions api (`/v1/chat/completions`) failed with 500 Internal Server Error.

The Ollama package's `ollama.chat(**data)` failed with 404 error, turns out it was pointing to `/chat` endpoint, afik Ollama has `/completions` endpoint. Due to that I got runtime error `RuntimeError: Attempted to call a sync iterator on an async stream` in the response in the browser. 

Did anyone faced this?

**Comment by rony432** [comment]
note for dev. increase reply timeout when ollama is active.

**Comment by vanpelt** [comment]
@hirenchauhan2 and @BeeTwenty those errors look like potentially a ollama compatibility issue.  Can you verify you're running a fairly recent version of Ollama or share what version you have?  You can get it by running:

```bash
ollama --version
```

**Comment by vanpelt** [comment]
Hey guys, I just updated the README [with instructions](https://github.com/wandb/openui?tab=readme-ov-file#docker-compose) for running via Docker Compose.  That might be easiest all be it slow.

**Comment by hirenchauhan2** [comment]
@vanpelt  Yeah, it was compatibility issue. I was using older version of Ollama `0.1.1`. I updated to newer version `0.1.30` and it started working. I don't have GPU on my machine, so it's slow which is understandable, but I keep getting the timeout error. Is this set in backend or frontend? I haven't checked the code yet hence asking this timeout thing. If we can remove the timeouts just for Ollama it would be better.
